# The directory where exitwp looks for wordpress export xml files.
wp_exports: wordpress-xml

# The target directory where all output is saved.
build_dir: build

# Output format: primary choices are html or markdown.
target_format: markdown

# The date format of the wikipedia export file.
# I'm not sure if this ever differs depending on wordpress localization.
# Wordpress is often so full of strange quirks so I wouldnt rule it out.
date_format: '%Y-%m-%d %H:%M:%S'

# Try to download and reloacate all images locally to the blog.
download_images: False

# Item types we don't want to import.
#item_type_filter: {attachment, nav_menu_item}
item_type_filter: {nav_menu_item}

# filter by any field type on the post.
# By default, we're filtering based on field "status" set to "draft"
item_field_filter: {status: draft}

taxonomies:
  # Filter taxonomies.
  filter: {}
  # Filter taxonomies entries.
  entry_filter: {category: Uncategorized}
  # Rename taxonomies when writing jekyll output format.
  name_mapping: {category: categories, post_tag: tags}

# Replace certain patterns in body
# Simply replace the key with its value
body_replace: {
  # '<pre.*?lang="(.*?)".*?>': '\n{% codeblock \1 lang:\1 %}\n',
  # '<pre.*?>': '\n{% codeblock %}\n',
  # '</pre>': '\n{% endcodeblock %}\n',

#    '[python]': '{% codeblock lang:python %}',
#    '[/python]': '{% endcodeblock %}',
  'http://linux-ha.sourceforge.jp/': '/',
  'http[s]?://linux-ha.osdn.jp/': '/',
  '/wp/wp-content/uploads/([^"]+(?:\.png|\.jpg))': '/assets/images/wp-content/\1',
  '/wp/wp-content/uploads/': '{{ site.lhajp_resources_url }}/wp-content/',
  # fix some links
  '/wp/\?p=(\d+)': '/wp/archives/\1',
  '(/wp/archives/\d+)/\d\b': '\1', # remove link to the specific page
  # canonicalize to abs. path for checking missing posts
  '"(archives/\d+\b)"': '"/wp/\1"',
  '\.\./\?attachment_id=': '/wp/?attachment_id=',
  ## pass 2: attachment_subst.txt
  '/wp/\?attachment_id=1273': '/wp/wp-content/uploads/eject.zip',
  '/wp/\?attachment_id=371': '/wp/wp-content/uploads/logo_pacemaker_200x100.png',
  '/wp/\?attachment_id=372': '/wp/wp-content/uploads/logo_pacemaker_300x150.png',
  '/wp/\?attachment_id=388': '/wp/wp-content/uploads/banner_pecemaker_88x31_01.jpg',
  '/wp/\?attachment_id=389': '/wp/wp-content/uploads/banner_pecemaker_236x60_011.jpg',
  '/wp/\?attachment_id=390': '/wp/wp-content/uploads/banner_pecemaker_728x90_01.jpg',
  '/wp/\?attachment_id=391': '/wp/wp-content/uploads/banner_pecemaker_1024x128_01.jpg',
  '/wp/\?attachment_id=392': '/wp/wp-content/uploads/banner_pecemaker_88x31_02.jpg',
  '/wp/\?attachment_id=393': '/wp/wp-content/uploads/banner_pecemaker_236x60_021.jpg',
  '/wp/\?attachment_id=394': '/wp/wp-content/uploads/banner_pecemaker_728x90_02.jpg',
  '/wp/\?attachment_id=395': '/wp/wp-content/uploads/banner_pecemaker_1024x128_02.jpg',
  '/wp/\?attachment_id=396': '/wp/wp-content/uploads/banner_pecemaker_88x31_03.jpg',
  '/wp/\?attachment_id=397': '/wp/wp-content/uploads/banner_pecemaker_236x60_031.jpg',
  '/wp/\?attachment_id=398': '/wp/wp-content/uploads/banner_pecemaker_728x90_03.jpg',
  '/wp/\?attachment_id=399': '/wp/wp-content/uploads/banner_pecemaker_1024x128_03.jpg',
  '/wp/\?attachment_id=400': '/wp/wp-content/uploads/banner_pecemaker_88x31_04.jpg',
  '/wp/\?attachment_id=401': '/wp/wp-content/uploads/banner_pecemaker_236x60_041.jpg',
  '/wp/\?attachment_id=402': '/wp/wp-content/uploads/banner_pecemaker_728x90_04.jpg',
  '/wp/\?attachment_id=403': '/wp/wp-content/uploads/banner_pecemaker_1024x128_04.jpg',
  '/wp/\?attachment_id=605': '/wp/wp-content/uploads/521492b28866dce52ea21dc3732ca9cf.swf',
  ## pass 2: missing_urls.txt - manually fixing
  '/wp/dl/find': '/wp/find',
  '/wp/dl/packages': '/wp/link/packages',
  '/wp/dl/pminstall_cent5/hb3_or_corosync': '/wp/manual/pminstall_cent5/hb3_or_corosync',
  '/wp/dl/pminstall_cent5/pm_simple_env': '/wp/manual/pminstall_cent5/pm_simple_env',
  '/wp/dl/pm-crm-setting': '/wp/archives/4224', # unpublished: /wp/manual/pm-crm-setting
  '/wp/dl/pminstall_cent5': '/wp/archives/4219', # unpublished: /wp/manual/pminstall_cent5
  '/wp/manual/ocfリソースエージェント開発者ガイド': '/wp/archives/4328', # unpublished:
  '/wp/archives/376[2-7]/(osc2013kyoto-qa0[2-7])': '/assets/images/wp-content/\1.png',
  # pass 2: rewrite links again for pass2
  #   leading '/?' is only for differenciate keys of pass1 and no meaning for matching
  '/?/wp/wp-content/uploads/([^"]+(?:\.png|\.jpg))': '/assets/images/wp-content/\1',
  '/?/wp/wp-content/uploads/': '{{ site.lhajp_resources_url }}/wp-content/',
  # fix Markdown conversion
  '<strong>\s+': '<strong>',
  '\s+</strong>': '</strong>',
  '<strong>\s*</strong>': '',
  '<fieldset([^>]*)>': '<pre\1>',
  '</fieldset>': '</pre>',
  # avoid to be handled as tags in HTMLParser
  '<(rsc|param|value)>': '&amp;lt;\1&amp;gt;', # 3419
  '<(domain|desturi|migrateuri|dname|number|string)>': '&amp;lt;\1&amp;gt;', # 3227
  '<((?:attribute|data|text)[^>]*)>': '&amp;lt;\1&amp;gt;', # 2994
  '</(attribute)>': '&amp;lt;/\1&amp;gt;', # 2994
  '<((?:xml|foo|hoge|stdio.h)[^>]*)>': '&amp;lt;\1&amp;gt;', # 175
  '</(xml|foo|hoge)>': '&amp;lt;/\1&amp;gt;', # 175
  # fix typo's before conversion so that html2text.py can detect invalid tags
  '<block>': '', # 3357
  '<storng>': '<strong>', # 3868
}
# embedding attachment_url into the body of the post
#   setting ''(empty string) to disable embedding
#attachment_url_format: ''
attachment_url_format: '<h3><a href="{attachment_url}">{title}</a></h3>'

# add wp_id prefix to the post filename
uid_wp_id_prefix: True
